# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tianxiao Ye
name: Tianxiao Ye
position: Robotics Engineer 
email: tye46@wisc.edu
description: |

  I am a researcher and engineer in Robot dynamics and control. I am pursuing my thesis-based Master's degree at the University of Wisconsin-Madison where I was advised by [Xiangru Xu](https://directory.engr.wisc.edu/me/Faculty/Xu_Xiangru/) and will graduate in May 2025.
  
  Before this, I spent a year as an exchange student at the University of Illinois at Chicago where I was advised by [A. Enis Cetin](https://ieeexplore.ieee.org/author/38186428600) and received my B.S. in Robotics Engineering from [Harbin Institute of Technology](https://en.wikipedia.org/wiki/Harbin_Institute_of_Technology) in 2023.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fuwafuwaboom.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: KeunhongP
github_username: fuwafuwaboom
google_scholar: qmcu3SUAAAAJ
google_analytics: G-PPPJ189F0F


# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
